#!/usr/bin/env bash
# This script displays number from 1 to 100

for numb in {1..100}
do
    if [ $((numb % 3)) -eq 0 ] && [ $(( numb % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((numb % 3 )) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((numb % 5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$numb"
    fi
done
