#!/usr/bin/env bash
#This script sorts the number of occurence of visitors by IP and HTTP status code, display the number of occurence
awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
