#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Get the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process was found
if [[ -n $pid ]]; then
    kill "$pid"
    echo "Terminated process $pid"
else
    echo "No running process found for 4-to_infinity_and_beyond"
fi
